#!/usr/bin/with-contenv bash

host="127.0.0.1"
port=${PORT:-3000}

# Verificar el resultado y salir con el código de estado apropiado
if s6-tcpclient -T 1000 ${host} ${port} true; then
  echo "Health check passed: Connected to ${host}:${port}"
  exit 0
else
  echo "Health check failed: Unable to connect to ${host}:${port}"
  exit 1
fi
